apiVersion: v1
kind: Pod
metadata:
  name: nde-copy-pvc-pod
spec:
  containers:
    - name: copy
      image: busybox
      command: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - name: nde-icefall-volume
          mountPath: /workspace/icefall/download
          subPath: download
        - name: nde-icefall-volume
          mountPath: /workspace/icefall/data
          subPath: data
  volumes:
    - name: nde-icefall-volume
      persistentVolumeClaim:
        claimName: nde-icefall-claim
