apiVersion: v1
kind: Pod
metadata:
  name: nde-pvc-inspect-nde
spec:
  containers:
  - name: nde-pvc-inspector-nde
    image: ubuntu:20.04
    command: ["sleep", "infinity"]
    securityContext: 
      runAsUser: 0
    volumeMounts:
    - mountPath: /pvc #has download and models inside
      name: nde-icefall-volume
  volumes:
  - name: nde-icefall-volume
    persistentVolumeClaim:
      claimName: nde-icefall-claim
  restartPolicy: Never
