apiVersion: v1
kind: Pod
metadata:
  name: nde-icefall-train-multisource33
  labels:
    user: nde
    project: polaris
  namespace: am-team
spec:
  schedulerName: ml-scheduler
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: accelerator
            operator: NotIn
            values:
            - a100
  restartPolicy: Never
  imagePullSecrets:
    - name: docker-melodis-readonly
  containers:
    - name: nde-icefall-container-train-multisource33
      image: docker.melodis.com/soundhound/zipformer_with_slurp_streaming:v26_multisource #v24_maskedintentloss270_lcs512 #v28_multisource
      # image: docker.melodis.com/soundhound/icefall:torch1.13.0-cuda11.6-updated-v3
      command:
        - "egs/librispeech/ASR/zipformer/train.py"
        - "--world-size"
        - "4" 
        - "--num-epochs"
        - "200"
        # - "--start-batch" ######
        # - "372000"
        - "--use-fp16"
        # - "1"
        - "0"
        - "--start-epoch" #####
        - "39" 
        - "--causal"
        - "1"
        - "--full-libri" ####
        - "1"
        - "--max-duration"
        - "500"
        # - "1000"
        - "--exp-dir"
        - "zipformer/exp-causal-multisource3"
        - "--base-lr"
        # - "0.005"
        # - "0.02"
        - "0.03"
        - "--left-context-frames" ######
        - "512"
        - "--context-size" #####
        - "4"
        - "--bpe-model"
        - "data2/lang_bpe_500_multisource/polaris_bpe500_lower.model"
        # - "data2/updated_tokenizer_slurp/slurp_bpe_NEW_500_without_intent.model"
        # - "data2/updated_tokenizer_slurp/slurp_bpe_NEW_predefined_intents.model"
        # - "data/lang_bpe_592/libri_intent_592.model"
        # - "--vocab-size"
        # - "500"
        - "--enable-musan"
        - "False"

      imagePullPolicy: Always
      tty: true
      env:
        - name: USER
          value: nde
      resources:
        requests:
          cpu: 26
          nvidia.com/gpu: 4
          memory: 40Gi
          ephemeral-storage: 40Gi
        limits:
          cpu: 26
          nvidia.com/gpu: 4
          memory: 40Gi
      volumeMounts:
        # - name: nde-icefall-volume
        #   mountPath: /workspace/icefall/download #using absolutepath here
        #   subPath: download #in the volume /whatever/download, using relative path here
        # - name: nde-icefall-volume
        #   mountPath: /workspace/icefall/data
        #   subPath: data

        - name: nfs-workspace-rw
          mountPath: /workspace/icefall/data
          subPath: LibriSpeech_nde/data

        - name: nfs-workspace-rw
          mountPath: /workspace/icefall/data2
          subPath: organized_slurp_data_pods_lower/data

        - name: nfs-workspace-polaris-rw
          mountPath: /workspace/icefall/datalibrispeech
          subPath: feats/polaris-majid-feat-librispeech-train

        - name: nfs-workspace-polaris-rw
          mountPath: /workspace/icefall/datafisher
          subPath: feats/polaris-majid-feat-fisher-16khz

        - name: nfs-workspace-polaris-rw
          mountPath: /workspace/icefall/datacommon
          subPath: feats/polaris-majid-feat-common-voice

        - name: nfs-workspace-rw
          mountPath: /workspace/icefall/zipformer/exp-causal-multisource3 #│ 2024-08-27 20:59:05,560 INFO [checkpoint.py:75] Saving checkpoint to zipformer/exp-causal/epoch-40.pt                                                        
          subPath: models_streaming/zipformer/v402_streaming_MultiSource3 #in the volume /whatever/models/zipformer/v0, saving the trained model from /workspace/icefall/egs/librispeech/ASR/zipformer/exp in pod while training to here
          readOnly: false
        - name: dshm
          mountPath: /dev/shm
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
  volumes:
    # - name: nde-icefall-volume
    #   persistentVolumeClaim:
    #     claimName: nde-icefall-claim
    - name: nfs-workspace-rw
      nfs:
        server: gpu.fss.us-phoenix-1.development.oci.soundhound.private
        path: /dev_gpu_filesystem/am-team/workspaces/nde
        readOnly: false
    
    - name: nfs-workspace-polaris-rw
      nfs:
        server: gpu.fss.us-phoenix-1.development.oci.soundhound.private
        path: /dev_gpu_filesystem/am-team/polaris
        readOnly: false

    - name: dshm
      emptyDir:
        medium: Memory
